name: 'Task Actions'
description: 'Task creation actions'
inputs:
  parent-label:
    description: If specified, will only run for parents with the specified lable
    required: false
  task-label:
    description: The label to apply to the newly created task
    required: true
    default: 'task'
runs:
  using: 'node12'
  main: 'index.js'