name: 'Task List Actions'
description: 'Automatically labels an opened issue on a task list'
inputs:
  parent-label:
    description: If specified, will only run for parents with the specified label
    required: false
  task-label:
    description: The label to apply to the opened issue
    required: true
    default: 'task'
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: alert-circle
  color: green